# Generated by Django 5.2.8 on 2025-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_review_description_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='Best'),
            preserve_default=False,
        ),
    ]
