# Generated by Django 5.2.8 on 2025-12-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
