# Generated by Django 5.2.8 on 2025-12-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
